In [37]:
import pandas as pd

In [103]:
df = pd.read_csv(r"C:\Users\USER\Downloads\details.csv.xls")
df

    101 Mohammed    24    Male    45000       IT  2023-01-15
0   102    Aisha  27.0  Female  52000.0       HR  2022-11-10
1   103    Rahul   NaN    Male  38000.0    Sales  2023-05-21
2   104    Priya  29.0  Female      NaN  Finance  2021-07-18
3   105     John  31.0    Male  60000.0       IT         NaN
4   106    Sneha  26.0  Female  47000.0       HR  2023-04-11
5   107     Arun  28.0    Male      NaN    Sales  2022-09-25
6   108      NaN  30.0  Female  55000.0  Finance  2021-10-12
7   109    David  25.0    Male  42000.0      NaN  2023-02-14
8   110    Meera   NaN  Female  48000.0       IT  2022-08-09
9   111      Ali  32.0    Male  62000.0       HR  2020-05-15
10  112  Fathima  29.0  Female      NaN  Finance  2021-11-30
11  113    Rohit  26.0    Male  41000.0    Sales  2023-03-17
12  114    Nisha  27.0  Female  53000.0       IT         NaN
13  115    Kiran  24.0    Male      NaN       HR  2022-06-28
14  116   Anjali   NaN  Female  50000.0  Finance  2023-01-19
15  117    Vijay  35.0    Male  70000.0       IT  2019-09-15
16  118    Pooja  28.0  Female  46000.0      NaN  2023-07-20
17  119    Samir  30.0    Male  58000.0    Sales         NaN
18  120     Neha  25.0  Female      NaN       HR  2022-04-16
19  121    Akash  27.0    Male  49000.0       IT  2023-06-01
20  122  Lakshmi  31.0  Female  61000.0  Finance  2021-12-22
21  123   Farhan   NaN    Male  45000.0    Sales  2022-03-18
22  124     Diya  29.0  Female  54000.0       HR         NaN
23  125    Kevin  26.0    Male      NaN       IT  2023-05-30
24  126     Riya  24.0  Female  43000.0  Finance  2022-02-14
25  127   Sanjay  33.0    Male  68000.0    Sales  2020-10-08
26  128      Anu   NaN  Female      NaN       HR  2023-01-07
27  129   Thomas  30.0    Male  59000.0       IT  2021-08-26
28  130   Reshma  27.0  Female  51000.0  Finance         NaN

In [104]:
df.columns=["Emp_ID","Name","Age","Gender","Salary","Department","Joining_Date"]
df

    Emp_ID     Name   Age  Gender   Salary Department Joining_Date
0      102    Aisha  27.0  Female  52000.0         HR   2022-11-10
1      103    Rahul   NaN    Male  38000.0      Sales   2023-05-21
2      104    Priya  29.0  Female      NaN    Finance   2021-07-18
3      105     John  31.0    Male  60000.0         IT          NaN
4      106    Sneha  26.0  Female  47000.0         HR   2023-04-11
5      107     Arun  28.0    Male      NaN      Sales   2022-09-25
6      108      NaN  30.0  Female  55000.0    Finance   2021-10-12
7      109    David  25.0    Male  42000.0        NaN   2023-02-14
8      110    Meera   NaN  Female  48000.0         IT   2022-08-09
9      111      Ali  32.0    Male  62000.0         HR   2020-05-15
10     112  Fathima  29.0  Female      NaN    Finance   2021-11-30
11     113    Rohit  26.0    Male  41000.0      Sales   2023-03-17
12     114    Nisha  27.0  Female  53000.0         IT          NaN
13     115    Kiran  24.0    Male      NaN         HR   2022-06-28
14     116   Anjali   NaN  Female  50000.0    Finance   2023-01-19
15     117    Vijay  35.0    Male  70000.0         IT   2019-09-15
16     118    Pooja  28.0  Female  46000.0        NaN   2023-07-20
17     119    Samir  30.0    Male  58000.0      Sales          NaN
18     120     Neha  25.0  Female      NaN         HR   2022-04-16
19     121    Akash  27.0    Male  49000.0         IT   2023-06-01
20     122  Lakshmi  31.0  Female  61000.0    Finance   2021-12-22
21     123   Farhan   NaN    Male  45000.0      Sales   2022-03-18
22     124     Diya  29.0  Female  54000.0         HR          NaN
23     125    Kevin  26.0    Male      NaN         IT   2023-05-30
24     126     Riya  24.0  Female  43000.0    Finance   2022-02-14
25     127   Sanjay  33.0    Male  68000.0      Sales   2020-10-08
26     128      Anu   NaN  Female      NaN         HR   2023-01-07
27     129   Thomas  30.0    Male  59000.0         IT   2021-08-26
28     130   Reshma  27.0  Female  51000.0    Finance          NaN

In [85]:
df.head(10)

   Emp_ID   Name   Age  Gender   Salary Department Joining_Date
0     102  Aisha  27.0  Female  52000.0         HR   2022-11-10
1     103  Rahul   NaN    Male  38000.0      Sales   2023-05-21
2     104  Priya  29.0  Female      NaN    Finance   2021-07-18
3     105   John  31.0    Male  60000.0         IT          NaN
4     106  Sneha  26.0  Female  47000.0         HR   2023-04-11
5     107   Arun  28.0    Male      NaN      Sales   2022-09-25
6     108    NaN  30.0  Female  55000.0    Finance   2021-10-12
7     109  David  25.0    Male  42000.0        NaN   2023-02-14
8     110  Meera   NaN  Female  48000.0         IT   2022-08-09
9     111    Ali  32.0    Male  62000.0         HR   2020-05-15

In [86]:
df.shape

(29, 7)

In [87]:
df.isnull().sum()

Emp_ID          0
Name            1
Age             5
Gender          0
Salary          7
Department      2
Joining_Date    5
dtype: int64

In [88]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

    Emp_ID     Name        Age  Gender   Salary Department Joining_Date
0      102    Aisha  27.000000  Female  52000.0         HR   2022-11-10
1      103    Rahul  28.291667    Male  38000.0      Sales   2023-05-21
2      104    Priya  29.000000  Female      NaN    Finance   2021-07-18
3      105     John  31.000000    Male  60000.0         IT          NaN
4      106    Sneha  26.000000  Female  47000.0         HR   2023-04-11
5      107     Arun  28.000000    Male      NaN      Sales   2022-09-25
6      108      NaN  30.000000  Female  55000.0    Finance   2021-10-12
7      109    David  25.000000    Male  42000.0        NaN   2023-02-14
8      110    Meera  28.291667  Female  48000.0         IT   2022-08-09
9      111      Ali  32.000000    Male  62000.0         HR   2020-05-15
10     112  Fathima  29.000000  Female      NaN    Finance   2021-11-30
11     113    Rohit  26.000000    Male  41000.0      Sales   2023-03-17
12     114    Nisha  27.000000  Female  53000.0         IT          NaN
13     115    Kiran  24.000000    Male      NaN         HR   2022-06-28
14     116   Anjali  28.291667  Female  50000.0    Finance   2023-01-19
15     117    Vijay  35.000000    Male  70000.0         IT   2019-09-15
16     118    Pooja  28.000000  Female  46000.0        NaN   2023-07-20
17     119    Samir  30.000000    Male  58000.0      Sales          NaN
18     120     Neha  25.000000  Female      NaN         HR   2022-04-16
19     121    Akash  27.000000    Male  49000.0         IT   2023-06-01
20     122  Lakshmi  31.000000  Female  61000.0    Finance   2021-12-22
21     123   Farhan  28.291667    Male  45000.0      Sales   2022-03-18
22     124     Diya  29.000000  Female  54000.0         HR          NaN
23     125    Kevin  26.000000    Male      NaN         IT   2023-05-30
24     126     Riya  24.000000  Female  43000.0    Finance   2022-02-14
25     127   Sanjay  33.000000    Male  68000.0      Sales   2020-10-08
26     128      Anu  28.291667  Female      NaN         HR   2023-01-07
27     129   Thomas  30.000000    Male  59000.0         IT   2021-08-26
28     130   Reshma  27.000000  Female  51000.0    Finance          NaN

In [89]:
df["Salary"]=df["Salary"].fillna(df["Salary"].median())
df

    Emp_ID     Name        Age  Gender   Salary Department Joining_Date
0      102    Aisha  27.000000  Female  52000.0         HR   2022-11-10
1      103    Rahul  28.291667    Male  38000.0      Sales   2023-05-21
2      104    Priya  29.000000  Female  51500.0    Finance   2021-07-18
3      105     John  31.000000    Male  60000.0         IT          NaN
4      106    Sneha  26.000000  Female  47000.0         HR   2023-04-11
5      107     Arun  28.000000    Male  51500.0      Sales   2022-09-25
6      108      NaN  30.000000  Female  55000.0    Finance   2021-10-12
7      109    David  25.000000    Male  42000.0        NaN   2023-02-14
8      110    Meera  28.291667  Female  48000.0         IT   2022-08-09
9      111      Ali  32.000000    Male  62000.0         HR   2020-05-15
10     112  Fathima  29.000000  Female  51500.0    Finance   2021-11-30
11     113    Rohit  26.000000    Male  41000.0      Sales   2023-03-17
12     114    Nisha  27.000000  Female  53000.0         IT          NaN
13     115    Kiran  24.000000    Male  51500.0         HR   2022-06-28
14     116   Anjali  28.291667  Female  50000.0    Finance   2023-01-19
15     117    Vijay  35.000000    Male  70000.0         IT   2019-09-15
16     118    Pooja  28.000000  Female  46000.0        NaN   2023-07-20
17     119    Samir  30.000000    Male  58000.0      Sales          NaN
18     120     Neha  25.000000  Female  51500.0         HR   2022-04-16
19     121    Akash  27.000000    Male  49000.0         IT   2023-06-01
20     122  Lakshmi  31.000000  Female  61000.0    Finance   2021-12-22
21     123   Farhan  28.291667    Male  45000.0      Sales   2022-03-18
22     124     Diya  29.000000  Female  54000.0         HR          NaN
23     125    Kevin  26.000000    Male  51500.0         IT   2023-05-30
24     126     Riya  24.000000  Female  43000.0    Finance   2022-02-14
25     127   Sanjay  33.000000    Male  68000.0      Sales   2020-10-08
26     128      Anu  28.291667  Female  51500.0         HR   2023-01-07
27     129   Thomas  30.000000    Male  59000.0         IT   2021-08-26
28     130   Reshma  27.000000  Female  51000.0    Finance          NaN

In [90]:
df["Name"]=df["Name"].fillna("unknown")
df

    Emp_ID     Name        Age  Gender   Salary Department Joining_Date
0      102    Aisha  27.000000  Female  52000.0         HR   2022-11-10
1      103    Rahul  28.291667    Male  38000.0      Sales   2023-05-21
2      104    Priya  29.000000  Female  51500.0    Finance   2021-07-18
3      105     John  31.000000    Male  60000.0         IT          NaN
4      106    Sneha  26.000000  Female  47000.0         HR   2023-04-11
5      107     Arun  28.000000    Male  51500.0      Sales   2022-09-25
6      108  unknown  30.000000  Female  55000.0    Finance   2021-10-12
7      109    David  25.000000    Male  42000.0        NaN   2023-02-14
8      110    Meera  28.291667  Female  48000.0         IT   2022-08-09
9      111      Ali  32.000000    Male  62000.0         HR   2020-05-15
10     112  Fathima  29.000000  Female  51500.0    Finance   2021-11-30
11     113    Rohit  26.000000    Male  41000.0      Sales   2023-03-17
12     114    Nisha  27.000000  Female  53000.0         IT          NaN
13     115    Kiran  24.000000    Male  51500.0         HR   2022-06-28
14     116   Anjali  28.291667  Female  50000.0    Finance   2023-01-19
15     117    Vijay  35.000000    Male  70000.0         IT   2019-09-15
16     118    Pooja  28.000000  Female  46000.0        NaN   2023-07-20
17     119    Samir  30.000000    Male  58000.0      Sales          NaN
18     120     Neha  25.000000  Female  51500.0         HR   2022-04-16
19     121    Akash  27.000000    Male  49000.0         IT   2023-06-01
20     122  Lakshmi  31.000000  Female  61000.0    Finance   2021-12-22
21     123   Farhan  28.291667    Male  45000.0      Sales   2022-03-18
22     124     Diya  29.000000  Female  54000.0         HR          NaN
23     125    Kevin  26.000000    Male  51500.0         IT   2023-05-30
24     126     Riya  24.000000  Female  43000.0    Finance   2022-02-14
25     127   Sanjay  33.000000    Male  68000.0      Sales   2020-10-08
26     128      Anu  28.291667  Female  51500.0         HR   2023-01-07
27     129   Thomas  30.000000    Male  59000.0         IT   2021-08-26
28     130   Reshma  27.000000  Female  51000.0    Finance          NaN

In [91]:
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])
df

    Emp_ID     Name        Age  Gender   Salary Department Joining_Date
0      102    Aisha  27.000000  Female  52000.0         HR   2022-11-10
1      103    Rahul  28.291667    Male  38000.0      Sales   2023-05-21
2      104    Priya  29.000000  Female  51500.0    Finance   2021-07-18
3      105     John  31.000000    Male  60000.0         IT          NaN
4      106    Sneha  26.000000  Female  47000.0         HR   2023-04-11
5      107     Arun  28.000000    Male  51500.0      Sales   2022-09-25
6      108  unknown  30.000000  Female  55000.0    Finance   2021-10-12
7      109    David  25.000000    Male  42000.0    Finance   2023-02-14
8      110    Meera  28.291667  Female  48000.0         IT   2022-08-09
9      111      Ali  32.000000    Male  62000.0         HR   2020-05-15
10     112  Fathima  29.000000  Female  51500.0    Finance   2021-11-30
11     113    Rohit  26.000000    Male  41000.0      Sales   2023-03-17
12     114    Nisha  27.000000  Female  53000.0         IT          NaN
13     115    Kiran  24.000000    Male  51500.0         HR   2022-06-28
14     116   Anjali  28.291667  Female  50000.0    Finance   2023-01-19
15     117    Vijay  35.000000    Male  70000.0         IT   2019-09-15
16     118    Pooja  28.000000  Female  46000.0    Finance   2023-07-20
17     119    Samir  30.000000    Male  58000.0      Sales          NaN
18     120     Neha  25.000000  Female  51500.0         HR   2022-04-16
19     121    Akash  27.000000    Male  49000.0         IT   2023-06-01
20     122  Lakshmi  31.000000  Female  61000.0    Finance   2021-12-22
21     123   Farhan  28.291667    Male  45000.0      Sales   2022-03-18
22     124     Diya  29.000000  Female  54000.0         HR          NaN
23     125    Kevin  26.000000    Male  51500.0         IT   2023-05-30
24     126     Riya  24.000000  Female  43000.0    Finance   2022-02-14
25     127   Sanjay  33.000000    Male  68000.0      Sales   2020-10-08
26     128      Anu  28.291667  Female  51500.0         HR   2023-01-07
27     129   Thomas  30.000000    Male  59000.0         IT   2021-08-26
28     130   Reshma  27.000000  Female  51000.0    Finance          NaN

In [92]:
df["Joining_Date"] = df["Joining_Date"].fillna("2023-01-01")
df

    Emp_ID     Name        Age  Gender   Salary Department Joining_Date
0      102    Aisha  27.000000  Female  52000.0         HR   2022-11-10
1      103    Rahul  28.291667    Male  38000.0      Sales   2023-05-21
2      104    Priya  29.000000  Female  51500.0    Finance   2021-07-18
3      105     John  31.000000    Male  60000.0         IT   2023-01-01
4      106    Sneha  26.000000  Female  47000.0         HR   2023-04-11
5      107     Arun  28.000000    Male  51500.0      Sales   2022-09-25
6      108  unknown  30.000000  Female  55000.0    Finance   2021-10-12
7      109    David  25.000000    Male  42000.0    Finance   2023-02-14
8      110    Meera  28.291667  Female  48000.0         IT   2022-08-09
9      111      Ali  32.000000    Male  62000.0         HR   2020-05-15
10     112  Fathima  29.000000  Female  51500.0    Finance   2021-11-30
11     113    Rohit  26.000000    Male  41000.0      Sales   2023-03-17
12     114    Nisha  27.000000  Female  53000.0         IT   2023-01-01
13     115    Kiran  24.000000    Male  51500.0         HR   2022-06-28
14     116   Anjali  28.291667  Female  50000.0    Finance   2023-01-19
15     117    Vijay  35.000000    Male  70000.0         IT   2019-09-15
16     118    Pooja  28.000000  Female  46000.0    Finance   2023-07-20
17     119    Samir  30.000000    Male  58000.0      Sales   2023-01-01
18     120     Neha  25.000000  Female  51500.0         HR   2022-04-16
19     121    Akash  27.000000    Male  49000.0         IT   2023-06-01
20     122  Lakshmi  31.000000  Female  61000.0    Finance   2021-12-22
21     123   Farhan  28.291667    Male  45000.0      Sales   2022-03-18
22     124     Diya  29.000000  Female  54000.0         HR   2023-01-01
23     125    Kevin  26.000000    Male  51500.0         IT   2023-05-30
24     126     Riya  24.000000  Female  43000.0    Finance   2022-02-14
25     127   Sanjay  33.000000    Male  68000.0      Sales   2020-10-08
26     128      Anu  28.291667  Female  51500.0         HR   2023-01-07
27     129   Thomas  30.000000    Male  59000.0         IT   2021-08-26
28     130   Reshma  27.000000  Female  51000.0    Finance   2023-01-01

In [93]:
print(df.isnull().sum())

Emp_ID          0
Name            0
Age             0
Gender          0
Salary          0
Department      0
Joining_Date    0
dtype: int64

In [94]:
df["Emp_ID"] = df["Emp_ID"].astype(int)

In [95]:
df["Age"] = df["Age"].astype(int)

In [96]:
df["Salary"] = df["Salary"].astype(float)

In [97]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

In [98]:
df["Gender"] = df["Gender"].astype("category")

In [99]:
df["Department"] = df["Department"].astype("category")

In [100]:
print(df.dtypes)

Emp_ID                   int64
Name                       str
Age                      int64
Gender                category
Salary                 float64
Department            category
Joining_Date    datetime64[us]
dtype: object

In [105]:
print(df[df.isnull().any(axis=1)])

    Emp_ID     Name   Age  Gender   Salary Department Joining_Date
1      103    Rahul   NaN    Male  38000.0      Sales   2023-05-21
2      104    Priya  29.0  Female      NaN    Finance   2021-07-18
3      105     John  31.0    Male  60000.0         IT          NaN
5      107     Arun  28.0    Male      NaN      Sales   2022-09-25
6      108      NaN  30.0  Female  55000.0    Finance   2021-10-12
7      109    David  25.0    Male  42000.0        NaN   2023-02-14
8      110    Meera   NaN  Female  48000.0         IT   2022-08-09
10     112  Fathima  29.0  Female      NaN    Finance   2021-11-30
12     114    Nisha  27.0  Female  53000.0         IT          NaN
13     115    Kiran  24.0    Male      NaN         HR   2022-06-28
14     116   Anjali   NaN  Female  50000.0    Finance   2023-01-19
16     118    Pooja  28.0  Female  46000.0        NaN   2023-07-20
17     119    Samir  30.0    Male  58000.0      Sales          NaN
18     120     Neha  25.0  Female      NaN         HR   2022-04-16
21     123   Farhan   NaN    Male  45000.0      Sales   2022-03-18
22     124     Diya  29.0  Female  54000.0         HR          NaN
23     125    Kevin  26.0    Male      NaN         IT   2023-05-30
26     128      Anu   NaN  Female      NaN         HR   2023-01-07
28     130   Reshma  27.0  Female  51000.0    Finance          NaN

In [106]:
print("Original Shape:", df.shape)

Original Shape: (29, 7)

In [107]:
df = df.dropna()
df

    Emp_ID     Name   Age  Gender   Salary Department Joining_Date
0      102    Aisha  27.0  Female  52000.0         HR   2022-11-10
4      106    Sneha  26.0  Female  47000.0         HR   2023-04-11
9      111      Ali  32.0    Male  62000.0         HR   2020-05-15
11     113    Rohit  26.0    Male  41000.0      Sales   2023-03-17
15     117    Vijay  35.0    Male  70000.0         IT   2019-09-15
19     121    Akash  27.0    Male  49000.0         IT   2023-06-01
20     122  Lakshmi  31.0  Female  61000.0    Finance   2021-12-22
24     126     Riya  24.0  Female  43000.0    Finance   2022-02-14
25     127   Sanjay  33.0    Male  68000.0      Sales   2020-10-08
27     129   Thomas  30.0    Male  59000.0         IT   2021-08-26

In [108]:
print("New Shape:", df.shape)

New Shape: (10, 7)

In [109]:
print(df)

    Emp_ID     Name   Age  Gender   Salary Department Joining_Date
0      102    Aisha  27.0  Female  52000.0         HR   2022-11-10
4      106    Sneha  26.0  Female  47000.0         HR   2023-04-11
9      111      Ali  32.0    Male  62000.0         HR   2020-05-15
11     113    Rohit  26.0    Male  41000.0      Sales   2023-03-17
15     117    Vijay  35.0    Male  70000.0         IT   2019-09-15
19     121    Akash  27.0    Male  49000.0         IT   2023-06-01
20     122  Lakshmi  31.0  Female  61000.0    Finance   2021-12-22
24     126     Riya  24.0  Female  43000.0    Finance   2022-02-14
25     127   Sanjay  33.0    Male  68000.0      Sales   2020-10-08
27     129   Thomas  30.0    Male  59000.0         IT   2021-08-26