In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\USER\Downloads\HR_Analytics_34227620.xlsx")

In [3]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [4]:
def age_category(age):
    if age < 25:
        return "Young"
    elif age <= 35:
        return "Adult"
    else:
        return "Senior"

df["Age_Category"] = df["Age"].apply(age_category)

print(df)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education EducationField  ...  \
0     Research & Development                 3          3  Life Sciences  ...
1                      Sales                10          3        Medical  ...
2                      Sales                 5          3      Marketing  ...
3     Research & Development                 5          2  Life Sciences  ...
4     Research & Development                 8          1        Medical  ...
...                      ...               ...        ...            ...  ...
1475  Research & Development                 7          3  Life Sciences  ...
1476                   Sales                28          3      Marketing  ...
1477                   Sales                16          4      Marketing  ...
1478                   Sales                 7          4      Marketing  ...
1479  Research & Development                 1          4        Medical  ...

      StandardHours  StockOptionLevel  TotalWorkingYears  \
0                80                 0                  0
1                80                 0                  0
2                80                 0                  0
3                80                 0                  0
4                80                 0                  0
...             ...               ...                ...
1475             80                 0                 33
1476             80                 0                 22
1477             80                 0                 10
1478             80                 1                 12
1479             80                 1                 19

     TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                        2                3               0
1                        2                3               0
2                        3                3               0
3                        2                3               0
4                        0                3               0
...                    ...              ...             ...
1475                     5                1              29
1476                     5                4              18
1477                     1                3               2
1478                     3                3              11
1479                     2                4               1

      YearsInCurrentRole YearsSinceLastPromotion  YearsWithCurrManager  \
0                      0                       0                   0.0
1                      0                       0                   0.0
2                      0                       0                   0.0
3                      0                       0                   0.0
4                      0                       0                   0.0
...                  ...                     ...                   ...
1475                   8                      11                  10.0
1476                  13                      13                  11.0
1477                   2                       2                   2.0
1478                   7                       1                   9.0
1479                   0                       0                   0.0

     Age_Category
0           Young
1           Young
2           Young
3           Young
4           Young
...           ...
1475       Senior
1476       Senior
1477       Senior
1478       Senior
1479       Senior

[1480 rows x 39 columns]

In [5]:
def travel_status(travel):
    if travel == "Travel_Rarely":
        return "Regular"
    elif travel == "Travel_Frequently":
        return "Frequent"
    else:
        return "No Travel"

df["Travel_Status"] = df["BusinessTravel"].apply(travel_status)

print(df)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education EducationField  ...  \
0     Research & Development                 3          3  Life Sciences  ...
1                      Sales                10          3        Medical  ...
2                      Sales                 5          3      Marketing  ...
3     Research & Development                 5          2  Life Sciences  ...
4     Research & Development                 8          1        Medical  ...
...                      ...               ...        ...            ...  ...
1475  Research & Development                 7          3  Life Sciences  ...
1476                   Sales                28          3      Marketing  ...
1477                   Sales                16          4      Marketing  ...
1478                   Sales                 7          4      Marketing  ...
1479  Research & Development                 1          4        Medical  ...

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  0                      2
1                    0                  0                      2
2                    0                  0                      3
3                    0                  0                      2
4                    0                  0                      0
...                ...                ...                    ...
1475                 0                 33                      5
1476                 0                 22                      5
1477                 0                 10                      1
1478                 1                 12                      3
1479                 1                 19                      2

     WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                  3               0                   0
1                  3               0                   0
2                  3               0                   0
3                  3               0                   0
4                  3               0                   0
...              ...             ...                 ...
1475               1              29                   8
1476               4              18                  13
1477               3               2                   2
1478               3              11                   7
1479               4               1                   0

      YearsSinceLastPromotion YearsWithCurrManager  Age_Category Travel_Status
0                           0                  0.0         Young       Regular
1                           0                  0.0         Young       Regular
2                           0                  0.0         Young      Frequent
3                           0                  0.0         Young     No Travel
4                           0                  0.0         Young     No Travel
...                       ...                  ...           ...           ...
1475                       11                 10.0        Senior       Regular
1476                       13                 11.0        Senior      Frequent
1477                        2                  2.0        Senior       Regular
1478                        1                  9.0        Senior       Regular
1479                        0                  0.0        Senior       Regular

[1480 rows x 40 columns]

In [6]:
def attrition_status(status):
    if status == "Yes":
        return "Left Company"
    else:
        return "Working"

df["Attrition_Status"] = df["Attrition"].apply(attrition_status)

print(df)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education EducationField  ...  \
0     Research & Development                 3          3  Life Sciences  ...
1                      Sales                10          3        Medical  ...
2                      Sales                 5          3      Marketing  ...
3     Research & Development                 5          2  Life Sciences  ...
4     Research & Development                 8          1        Medical  ...
...                      ...               ...        ...            ...  ...
1475  Research & Development                 7          3  Life Sciences  ...
1476                   Sales                28          3      Marketing  ...
1477                   Sales                16          4      Marketing  ...
1478                   Sales                 7          4      Marketing  ...
1479  Research & Development                 1          4        Medical  ...

      TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                     0                      2                3
1                     0                      2                3
2                     0                      3                3
3                     0                      2                3
4                     0                      0                3
...                 ...                    ...              ...
1475                 33                      5                1
1476                 22                      5                4
1477                 10                      1                3
1478                 12                      3                3
1479                 19                      2                4

     YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                 0                   0                        0
1                 0                   0                        0
2                 0                   0                        0
3                 0                   0                        0
4                 0                   0                        0
...             ...                 ...                      ...
1475             29                   8                       11
1476             18                  13                       13
1477              2                   2                        2
1478             11                   7                        1
1479              1                   0                        0

      YearsWithCurrManager Age_Category  Travel_Status Attrition_Status
0                      0.0        Young        Regular     Left Company
1                      0.0        Young        Regular          Working
2                      0.0        Young       Frequent     Left Company
3                      0.0        Young      No Travel          Working
4                      0.0        Young      No Travel     Left Company
...                    ...          ...            ...              ...
1475                  10.0       Senior        Regular          Working
1476                  11.0       Senior       Frequent          Working
1477                   2.0       Senior        Regular          Working
1478                   9.0       Senior        Regular          Working
1479                   0.0       Senior        Regular          Working

[1480 rows x 41 columns]

In [7]:
df["Department"] = df["Department"].apply(lambda x: x.upper())

print(df)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education EducationField  ...  \
0     RESEARCH & DEVELOPMENT                 3          3  Life Sciences  ...
1                      SALES                10          3        Medical  ...
2                      SALES                 5          3      Marketing  ...
3     RESEARCH & DEVELOPMENT                 5          2  Life Sciences  ...
4     RESEARCH & DEVELOPMENT                 8          1        Medical  ...
...                      ...               ...        ...            ...  ...
1475  RESEARCH & DEVELOPMENT                 7          3  Life Sciences  ...
1476                   SALES                28          3      Marketing  ...
1477                   SALES                16          4      Marketing  ...
1478                   SALES                 7          4      Marketing  ...
1479  RESEARCH & DEVELOPMENT                 1          4        Medical  ...

      TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0                     0                      2                3
1                     0                      2                3
2                     0                      3                3
3                     0                      2                3
4                     0                      0                3
...                 ...                    ...              ...
1475                 33                      5                1
1476                 22                      5                4
1477                 10                      1                3
1478                 12                      3                3
1479                 19                      2                4

     YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                 0                   0                        0
1                 0                   0                        0
2                 0                   0                        0
3                 0                   0                        0
4                 0                   0                        0
...             ...                 ...                      ...
1475             29                   8                       11
1476             18                  13                       13
1477              2                   2                        2
1478             11                   7                        1
1479              1                   0                        0

      YearsWithCurrManager Age_Category  Travel_Status Attrition_Status
0                      0.0        Young        Regular     Left Company
1                      0.0        Young        Regular          Working
2                      0.0        Young       Frequent     Left Company
3                      0.0        Young      No Travel          Working
4                      0.0        Young      No Travel     Left Company
...                    ...          ...            ...              ...
1475                  10.0       Senior        Regular          Working
1476                  11.0       Senior       Frequent          Working
1477                   2.0       Senior        Regular          Working
1478                   9.0       Senior        Regular          Working
1479                   0.0       Senior        Regular          Working

[1480 rows x 41 columns]

In [8]:
df["DailyRate_Bonus"] = df["DailyRate"] * 1.10

print(df)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education EducationField  ...  \
0     RESEARCH & DEVELOPMENT                 3          3  Life Sciences  ...
1                      SALES                10          3        Medical  ...
2                      SALES                 5          3      Marketing  ...
3     RESEARCH & DEVELOPMENT                 5          2  Life Sciences  ...
4     RESEARCH & DEVELOPMENT                 8          1        Medical  ...
...                      ...               ...        ...            ...  ...
1475  RESEARCH & DEVELOPMENT                 7          3  Life Sciences  ...
1476                   SALES                28          3      Marketing  ...
1477                   SALES                16          4      Marketing  ...
1478                   SALES                 7          4      Marketing  ...
1479  RESEARCH & DEVELOPMENT                 1          4        Medical  ...

      TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                         2                3               0
1                         2                3               0
2                         3                3               0
3                         2                3               0
4                         0                3               0
...                     ...              ...             ...
1475                      5                1              29
1476                      5                4              18
1477                      1                3               2
1478                      3                3              11
1479                      2                4               1

     YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                     0                        0                   0.0
1                     0                        0                   0.0
2                     0                        0                   0.0
3                     0                        0                   0.0
4                     0                        0                   0.0
...                 ...                      ...                   ...
1475                  8                       11                  10.0
1476                 13                       13                  11.0
1477                  2                        2                   2.0
1478                  7                        1                   9.0
1479                  0                        0                   0.0

      Age_Category Travel_Status  Attrition_Status DailyRate_Bonus
0            Young       Regular      Left Company           253.0
1            Young       Regular           Working           893.2
2            Young      Frequent      Left Company          1436.6
3            Young     No Travel           Working           315.7
4            Young     No Travel      Left Company           271.7
...            ...           ...               ...             ...
1475        Senior       Regular           Working           464.2
1476        Senior      Frequent           Working          1648.9
1477        Senior       Regular           Working          1296.9
1478        Senior       Regular           Working           765.6
1479        Senior       Regular           Working           407.0

[1480 rows x 42 columns]

In [9]:
def distance_category(distance):
    if distance <= 5:
        return "Near"
    elif distance <= 15:
        return "Medium"
    else:
        return "Far"

df["Distance_Category"] = df["DistanceFromHome"].apply(distance_category)

print(df)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education EducationField  ...  \
0     RESEARCH & DEVELOPMENT                 3          3  Life Sciences  ...
1                      SALES                10          3        Medical  ...
2                      SALES                 5          3      Marketing  ...
3     RESEARCH & DEVELOPMENT                 5          2  Life Sciences  ...
4     RESEARCH & DEVELOPMENT                 8          1        Medical  ...
...                      ...               ...        ...            ...  ...
1475  RESEARCH & DEVELOPMENT                 7          3  Life Sciences  ...
1476                   SALES                28          3      Marketing  ...
1477                   SALES                16          4      Marketing  ...
1478                   SALES                 7          4      Marketing  ...
1479  RESEARCH & DEVELOPMENT                 1          4        Medical  ...

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                   3               0                   0
1                   3               0                   0
2                   3               0                   0
3                   3               0                   0
4                   3               0                   0
...               ...             ...                 ...
1475                1              29                   8
1476                4              18                  13
1477                3               2                   2
1478                3              11                   7
1479                4               1                   0

     YearsSinceLastPromotion  YearsWithCurrManager  Age_Category  \
0                          0                   0.0         Young
1                          0                   0.0         Young
2                          0                   0.0         Young
3                          0                   0.0         Young
4                          0                   0.0         Young
...                      ...                   ...           ...
1475                      11                  10.0        Senior
1476                      13                  11.0        Senior
1477                       2                   2.0        Senior
1478                       1                   9.0        Senior
1479                       0                   0.0        Senior

      Travel_Status Attrition_Status  DailyRate_Bonus Distance_Category
0           Regular     Left Company            253.0              Near
1           Regular          Working            893.2            Medium
2          Frequent     Left Company           1436.6              Near
3         No Travel          Working            315.7              Near
4         No Travel     Left Company            271.7            Medium
...             ...              ...              ...               ...
1475        Regular          Working            464.2            Medium
1476       Frequent          Working           1648.9               Far
1477        Regular          Working           1296.9               Far
1478        Regular          Working            765.6            Medium
1479        Regular          Working            407.0              Near

[1480 rows x 43 columns]

In [10]:
def experience(years):
    if years >= 10:
        return "Experienced"
    else:
        return "Fresher"

df["Experience_Status"] = df["TotalWorkingYears"].apply(experience)

print(df)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education EducationField  ...  \
0     RESEARCH & DEVELOPMENT                 3          3  Life Sciences  ...
1                      SALES                10          3        Medical  ...
2                      SALES                 5          3      Marketing  ...
3     RESEARCH & DEVELOPMENT                 5          2  Life Sciences  ...
4     RESEARCH & DEVELOPMENT                 8          1        Medical  ...
...                      ...               ...        ...            ...  ...
1475  RESEARCH & DEVELOPMENT                 7          3  Life Sciences  ...
1476                   SALES                28          3      Marketing  ...
1477                   SALES                16          4      Marketing  ...
1478                   SALES                 7          4      Marketing  ...
1479  RESEARCH & DEVELOPMENT                 1          4        Medical  ...

      YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                  0                   0                        0
1                  0                   0                        0
2                  0                   0                        0
3                  0                   0                        0
4                  0                   0                        0
...              ...                 ...                      ...
1475              29                   8                       11
1476              18                  13                       13
1477               2                   2                        2
1478              11                   7                        1
1479               1                   0                        0

     YearsWithCurrManager  Age_Category  Travel_Status  Attrition_Status  \
0                     0.0         Young        Regular      Left Company
1                     0.0         Young        Regular           Working
2                     0.0         Young       Frequent      Left Company
3                     0.0         Young      No Travel           Working
4                     0.0         Young      No Travel      Left Company
...                   ...           ...            ...               ...
1475                 10.0        Senior        Regular           Working
1476                 11.0        Senior       Frequent           Working
1477                  2.0        Senior        Regular           Working
1478                  9.0        Senior        Regular           Working
1479                  0.0        Senior        Regular           Working

     DailyRate_Bonus  Distance_Category Experience_Status
0              253.0               Near           Fresher
1              893.2             Medium           Fresher
2             1436.6               Near           Fresher
3              315.7               Near           Fresher
4              271.7             Medium           Fresher
...              ...                ...               ...
1475           464.2             Medium       Experienced
1476          1648.9                Far       Experienced
1477          1296.9                Far       Experienced
1478           765.6             Medium       Experienced
1479           407.0               Near       Experienced

[1480 rows x 44 columns]

In [11]:
print(df.loc[df["Age_Category"] == "Senior"])

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
734    RM010   36    36-45        No      Travel_Rarely       1299
735    RM022   36    36-45       Yes      Travel_Rarely       1218
736    RM039   36    36-45        No      Travel_Rarely        852
737    RM065   36    36-45        No      Travel_Rarely       1223
738    RM067   36    36-45        No  Travel_Frequently       1195
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education    EducationField  \
734   RESEARCH & DEVELOPMENT                27          3           Medical
735                    SALES                 9          4     Life Sciences
736   RESEARCH & DEVELOPMENT                 5          4     Life Sciences
737   RESEARCH & DEVELOPMENT                 8          3  Technical Degree
738   RESEARCH & DEVELOPMENT                11          3     Life Sciences
...                      ...               ...        ...               ...
1475  RESEARCH & DEVELOPMENT                 7          3     Life Sciences
1476                   SALES                28          3         Marketing
1477                   SALES                16          4         Marketing
1478                   SALES                 7          4         Marketing
1479  RESEARCH & DEVELOPMENT                 1          4           Medical

      ...  YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
734   ...               7                   7                        7
735   ...               5                   3                        0
736   ...               1                   1                        0
737   ...              17                  14                       12
738   ...               6                   5                        0
...   ...             ...                 ...                      ...
1475  ...              29                   8                       11
1476  ...              18                  13                       13
1477  ...               2                   2                        2
1478  ...              11                   7                        1
1479  ...               1                   0                        0

     YearsWithCurrManager  Age_Category  Travel_Status  Attrition_Status  \
734                   7.0        Senior        Regular           Working
735                   3.0        Senior        Regular      Left Company
736                   0.0        Senior        Regular           Working
737                   8.0        Senior        Regular           Working
738                   3.0        Senior       Frequent           Working
...                   ...           ...            ...               ...
1475                 10.0        Senior        Regular           Working
1476                 11.0        Senior       Frequent           Working
1477                  2.0        Senior        Regular           Working
1478                  9.0        Senior        Regular           Working
1479                  0.0        Senior        Regular           Working

     DailyRate_Bonus  Distance_Category Experience_Status
734           1428.9                Far       Experienced
735           1339.8             Medium       Experienced
736            937.2               Near           Fresher
737           1345.3             Medium       Experienced
738           1314.5             Medium           Fresher
...              ...                ...               ...
1475           464.2             Medium       Experienced
1476          1648.9                Far       Experienced
1477          1296.9                Far       Experienced
1478           765.6             Medium       Experienced
1479           407.0               Near       Experienced

[746 rows x 44 columns]

In [15]:
new_emp = pd.DataFrame({
    "EmpID":["RM2000","RM2001"],
    "Age":[30,27],
    "AgeGroup":["26-35","26-35"],
    "Attrition":["No","Yes"]
})
new_emp

    EmpID  Age AgeGroup Attrition
0  RM2000   30    26-35        No
1  RM2001   27    26-35       Yes

In [16]:
result = pd.concat([df, new_emp], axis=0)

print(result)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely      230.0
1      RM302   18    18-25        No      Travel_Rarely      812.0
2      RM458   18    18-25       Yes  Travel_Frequently     1306.0
3      RM728   18    18-25        No         Non-Travel      287.0
4      RM829   18    18-25       Yes         Non-Travel      247.0
...      ...  ...      ...       ...                ...        ...
1477   RM537   60      55+        No      Travel_Rarely     1179.0
1478   RM880   60      55+        No      Travel_Rarely      696.0
1479  RM1210   60      55+        No      Travel_Rarely      370.0
0     RM2000   30    26-35        No                NaN        NaN
1     RM2001   27    26-35       Yes                NaN        NaN

                  Department  DistanceFromHome  Education EducationField  ...  \
0     RESEARCH & DEVELOPMENT               3.0        3.0  Life Sciences  ...
1                      SALES              10.0        3.0        Medical  ...
2                      SALES               5.0        3.0      Marketing  ...
3     RESEARCH & DEVELOPMENT               5.0        2.0  Life Sciences  ...
4     RESEARCH & DEVELOPMENT               8.0        1.0        Medical  ...
...                      ...               ...        ...            ...  ...
1477                   SALES              16.0        4.0      Marketing  ...
1478                   SALES               7.0        4.0      Marketing  ...
1479  RESEARCH & DEVELOPMENT               1.0        4.0        Medical  ...
0                        NaN               NaN        NaN            NaN  ...
1                        NaN               NaN        NaN            NaN  ...

      YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0                0.0                 0.0                      0.0
1                0.0                 0.0                      0.0
2                0.0                 0.0                      0.0
3                0.0                 0.0                      0.0
4                0.0                 0.0                      0.0
...              ...                 ...                      ...
1477             2.0                 2.0                      2.0
1478            11.0                 7.0                      1.0
1479             1.0                 0.0                      0.0
0                NaN                 NaN                      NaN
1                NaN                 NaN                      NaN

     YearsWithCurrManager  Age_Category  Travel_Status  Attrition_Status  \
0                     0.0         Young        Regular      Left Company
1                     0.0         Young        Regular           Working
2                     0.0         Young       Frequent      Left Company
3                     0.0         Young      No Travel           Working
4                     0.0         Young      No Travel      Left Company
...                   ...           ...            ...               ...
1477                  2.0        Senior        Regular           Working
1478                  9.0        Senior        Regular           Working
1479                  0.0        Senior        Regular           Working
0                     NaN           NaN            NaN               NaN
1                     NaN           NaN            NaN               NaN

     DailyRate_Bonus  Distance_Category Experience_Status
0              253.0               Near           Fresher
1              893.2             Medium           Fresher
2             1436.6               Near           Fresher
3              315.7               Near           Fresher
4              271.7             Medium           Fresher
...              ...                ...               ...
1477          1296.9                Far       Experienced
1478           765.6             Medium       Experienced
1479           407.0               Near       Experienced
0                NaN                NaN               NaN
1                NaN                NaN               NaN

[1482 rows x 44 columns]

In [17]:
result = pd.concat([df.head(10), df.tail(10)])

print(result)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
5      RM973   18    18-25        No         Non-Travel       1124
6     RM1154   18    18-25       Yes  Travel_Frequently        544
7     RM1312   18    18-25        No         Non-Travel       1431
8      RM128   19    18-25       Yes      Travel_Rarely        528
9      RM150   19    18-25        No      Travel_Rarely       1181
1470   RM233   59      55+        No      Travel_Rarely        818
1471   RM744   59      55+        No      Travel_Rarely        715
1472   RM759   59      55+        No      Travel_Rarely       1089
1473   RM898   59      55+        No      Travel_Rarely        326
1474   RM920   59      55+        No      Travel_Rarely       1429
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education    EducationField  \
0     RESEARCH & DEVELOPMENT                 3          3     Life Sciences
1                      SALES                10          3           Medical
2                      SALES                 5          3         Marketing
3     RESEARCH & DEVELOPMENT                 5          2     Life Sciences
4     RESEARCH & DEVELOPMENT                 8          1           Medical
5     RESEARCH & DEVELOPMENT                 1          3     Life Sciences
6                      SALES                 3          2           Medical
7     RESEARCH & DEVELOPMENT                14          3           Medical
8                      SALES                22          1         Marketing
9     RESEARCH & DEVELOPMENT                 3          1           Medical
1470         HUMAN RESOURCES                 6          2           Medical
1471  RESEARCH & DEVELOPMENT                 2          3     Life Sciences
1472                   SALES                 1          2  Technical Degree
1473                   SALES                 3          3     Life Sciences
1474  RESEARCH & DEVELOPMENT                18          4           Medical
1475  RESEARCH & DEVELOPMENT                 7          3     Life Sciences
1476                   SALES                28          3         Marketing
1477                   SALES                16          4         Marketing
1478                   SALES                 7          4         Marketing
1479  RESEARCH & DEVELOPMENT                 1          4           Medical

      ...  YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0     ...               0                   0                        0
1     ...               0                   0                        0
2     ...               0                   0                        0
3     ...               0                   0                        0
4     ...               0                   0                        0
5     ...               0                   0                        0
6     ...               0                   0                        0
7     ...               0                   0                        0
8     ...               0                   0                        0
9     ...               1                   0                        0
1470  ...               2                   2                        2
1471  ...               5                   3                        4
1472  ...               6                   4                        0
1473  ...               6                   1                        0
1474  ...               9                   7                        5
1475  ...              29                   8                       11
1476  ...              18                  13                       13
1477  ...               2                   2                        2
1478  ...              11                   7                        1
1479  ...               1                   0                        0

     YearsWithCurrManager  Age_Category  Travel_Status  Attrition_Status  \
0                     0.0         Young        Regular      Left Company
1                     0.0         Young        Regular           Working
2                     0.0         Young       Frequent      Left Company
3                     0.0         Young      No Travel           Working
4                     0.0         Young      No Travel      Left Company
5                     0.0         Young      No Travel           Working
6                     0.0         Young       Frequent      Left Company
7                     0.0         Young      No Travel           Working
8                     0.0         Young        Regular      Left Company
9                     0.0         Young        Regular           Working
1470                  2.0        Senior        Regular           Working
1471                  3.0        Senior        Regular           Working
1472                  4.0        Senior        Regular           Working
1473                  5.0        Senior        Regular           Working
1474                  4.0        Senior        Regular           Working
1475                 10.0        Senior        Regular           Working
1476                 11.0        Senior       Frequent           Working
1477                  2.0        Senior        Regular           Working
1478                  9.0        Senior        Regular           Working
1479                  0.0        Senior        Regular           Working

     DailyRate_Bonus  Distance_Category Experience_Status
0              253.0               Near           Fresher
1              893.2             Medium           Fresher
2             1436.6               Near           Fresher
3              315.7               Near           Fresher
4              271.7             Medium           Fresher
5             1236.4               Near           Fresher
6              598.4               Near           Fresher
7             1574.1             Medium           Fresher
8              580.8                Far           Fresher
9             1299.1               Near           Fresher
1470           899.8             Medium           Fresher
1471           786.5               Near       Experienced
1472          1197.9               Near       Experienced
1473           358.6               Near       Experienced
1474          1571.9                Far       Experienced
1475           464.2             Medium       Experienced
1476          1648.9                Far       Experienced
1477          1296.9                Far       Experienced
1478           765.6             Medium       Experienced
1479           407.0               Near       Experienced

[20 rows x 44 columns]

In [18]:
result = pd.concat([df, new_emp], axis=1)

print(result)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education EducationField  ...  \
0     RESEARCH & DEVELOPMENT                 3          3  Life Sciences  ...
1                      SALES                10          3        Medical  ...
2                      SALES                 5          3      Marketing  ...
3     RESEARCH & DEVELOPMENT                 5          2  Life Sciences  ...
4     RESEARCH & DEVELOPMENT                 8          1        Medical  ...
...                      ...               ...        ...            ...  ...
1475  RESEARCH & DEVELOPMENT                 7          3  Life Sciences  ...
1476                   SALES                28          3      Marketing  ...
1477                   SALES                16          4      Marketing  ...
1478                   SALES                 7          4      Marketing  ...
1479  RESEARCH & DEVELOPMENT                 1          4        Medical  ...

      Age_Category  Travel_Status  Attrition_Status DailyRate_Bonus  \
0            Young        Regular      Left Company           253.0
1            Young        Regular           Working           893.2
2            Young       Frequent      Left Company          1436.6
3            Young      No Travel           Working           315.7
4            Young      No Travel      Left Company           271.7
...            ...            ...               ...             ...
1475        Senior        Regular           Working           464.2
1476        Senior       Frequent           Working          1648.9
1477        Senior        Regular           Working          1296.9
1478        Senior        Regular           Working           765.6
1479        Senior        Regular           Working           407.0

      Distance_Category  Experience_Status   EmpID   Age  AgeGroup Attrition
0                  Near            Fresher  RM2000  30.0     26-35        No
1                Medium            Fresher  RM2001  27.0     26-35       Yes
2                  Near            Fresher     NaN   NaN       NaN       NaN
3                  Near            Fresher     NaN   NaN       NaN       NaN
4                Medium            Fresher     NaN   NaN       NaN       NaN
...                 ...                ...     ...   ...       ...       ...
1475             Medium        Experienced     NaN   NaN       NaN       NaN
1476                Far        Experienced     NaN   NaN       NaN       NaN
1477                Far        Experienced     NaN   NaN       NaN       NaN
1478             Medium        Experienced     NaN   NaN       NaN       NaN
1479               Near        Experienced     NaN   NaN       NaN       NaN

[1480 rows x 48 columns]

In [19]:
result = result.reset_index(drop=True)

print(result)

       EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0      RM297   18    18-25       Yes      Travel_Rarely        230
1      RM302   18    18-25        No      Travel_Rarely        812
2      RM458   18    18-25       Yes  Travel_Frequently       1306
3      RM728   18    18-25        No         Non-Travel        287
4      RM829   18    18-25       Yes         Non-Travel        247
...      ...  ...      ...       ...                ...        ...
1475   RM412   60      55+        No      Travel_Rarely        422
1476   RM428   60      55+        No  Travel_Frequently       1499
1477   RM537   60      55+        No      Travel_Rarely       1179
1478   RM880   60      55+        No      Travel_Rarely        696
1479  RM1210   60      55+        No      Travel_Rarely        370

                  Department  DistanceFromHome  Education EducationField  ...  \
0     RESEARCH & DEVELOPMENT                 3          3  Life Sciences  ...
1                      SALES                10          3        Medical  ...
2                      SALES                 5          3      Marketing  ...
3     RESEARCH & DEVELOPMENT                 5          2  Life Sciences  ...
4     RESEARCH & DEVELOPMENT                 8          1        Medical  ...
...                      ...               ...        ...            ...  ...
1475  RESEARCH & DEVELOPMENT                 7          3  Life Sciences  ...
1476                   SALES                28          3      Marketing  ...
1477                   SALES                16          4      Marketing  ...
1478                   SALES                 7          4      Marketing  ...
1479  RESEARCH & DEVELOPMENT                 1          4        Medical  ...

      Age_Category  Travel_Status  Attrition_Status DailyRate_Bonus  \
0            Young        Regular      Left Company           253.0
1            Young        Regular           Working           893.2
2            Young       Frequent      Left Company          1436.6
3            Young      No Travel           Working           315.7
4            Young      No Travel      Left Company           271.7
...            ...            ...               ...             ...
1475        Senior        Regular           Working           464.2
1476        Senior       Frequent           Working          1648.9
1477        Senior        Regular           Working          1296.9
1478        Senior        Regular           Working           765.6
1479        Senior        Regular           Working           407.0

      Distance_Category  Experience_Status   EmpID   Age  AgeGroup Attrition
0                  Near            Fresher  RM2000  30.0     26-35        No
1                Medium            Fresher  RM2001  27.0     26-35       Yes
2                  Near            Fresher     NaN   NaN       NaN       NaN
3                  Near            Fresher     NaN   NaN       NaN       NaN
4                Medium            Fresher     NaN   NaN       NaN       NaN
...                 ...                ...     ...   ...       ...       ...
1475             Medium        Experienced     NaN   NaN       NaN       NaN
1476                Far        Experienced     NaN   NaN       NaN       NaN
1477                Far        Experienced     NaN   NaN       NaN       NaN
1478             Medium        Experienced     NaN   NaN       NaN       NaN
1479               Near        Experienced     NaN   NaN       NaN       NaN

[1480 rows x 48 columns]

In [20]:
print(result.shape)

(1480, 48)

In [22]:
salary = pd.DataFrame({
    "MonthlyBonus":[5000,7000,4000,8000,6000]
}, index=[0,1,2,3,4])
salary

   MonthlyBonus
0          5000
1          7000
2          4000
3          8000
4          6000

In [23]:
result = df.head().join(salary)

print(result)

   EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0  RM297   18    18-25       Yes      Travel_Rarely        230
1  RM302   18    18-25        No      Travel_Rarely        812
2  RM458   18    18-25       Yes  Travel_Frequently       1306
3  RM728   18    18-25        No         Non-Travel        287
4  RM829   18    18-25       Yes         Non-Travel        247

               Department  DistanceFromHome  Education EducationField  ...  \
0  RESEARCH & DEVELOPMENT                 3          3  Life Sciences  ...
1                   SALES                10          3        Medical  ...
2                   SALES                 5          3      Marketing  ...
3  RESEARCH & DEVELOPMENT                 5          2  Life Sciences  ...
4  RESEARCH & DEVELOPMENT                 8          1        Medical  ...

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                   0                        0                   0.0
1                   0                        0                   0.0
2                   0                        0                   0.0
3                   0                        0                   0.0
4                   0                        0                   0.0

  Age_Category  Travel_Status  Attrition_Status  DailyRate_Bonus  \
0        Young        Regular      Left Company            253.0
1        Young        Regular           Working            893.2
2        Young       Frequent      Left Company           1436.6
3        Young      No Travel           Working            315.7
4        Young      No Travel      Left Company            271.7

  Distance_Category  Experience_Status MonthlyBonus
0              Near            Fresher         5000
1            Medium            Fresher         7000
2              Near            Fresher         4000
3              Near            Fresher         8000
4            Medium            Fresher         6000

[5 rows x 45 columns]

In [25]:
result = df.head().join(salary, how="left")

print(result)

   EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0  RM297   18    18-25       Yes      Travel_Rarely        230
1  RM302   18    18-25        No      Travel_Rarely        812
2  RM458   18    18-25       Yes  Travel_Frequently       1306
3  RM728   18    18-25        No         Non-Travel        287
4  RM829   18    18-25       Yes         Non-Travel        247

               Department  DistanceFromHome  Education EducationField  ...  \
0  RESEARCH & DEVELOPMENT                 3          3  Life Sciences  ...
1                   SALES                10          3        Medical  ...
2                   SALES                 5          3      Marketing  ...
3  RESEARCH & DEVELOPMENT                 5          2  Life Sciences  ...
4  RESEARCH & DEVELOPMENT                 8          1        Medical  ...

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                   0                        0                   0.0
1                   0                        0                   0.0
2                   0                        0                   0.0
3                   0                        0                   0.0
4                   0                        0                   0.0

  Age_Category  Travel_Status  Attrition_Status  DailyRate_Bonus  \
0        Young        Regular      Left Company            253.0
1        Young        Regular           Working            893.2
2        Young       Frequent      Left Company           1436.6
3        Young      No Travel           Working            315.7
4        Young      No Travel      Left Company            271.7

  Distance_Category  Experience_Status MonthlyBonus
0              Near            Fresher         5000
1            Medium            Fresher         7000
2              Near            Fresher         4000
3              Near            Fresher         8000
4            Medium            Fresher         6000

[5 rows x 45 columns]

In [26]:
result = df.head().join(salary, how="inner")

print(result)

   EmpID  Age AgeGroup Attrition     BusinessTravel  DailyRate  \
0  RM297   18    18-25       Yes      Travel_Rarely        230
1  RM302   18    18-25        No      Travel_Rarely        812
2  RM458   18    18-25       Yes  Travel_Frequently       1306
3  RM728   18    18-25        No         Non-Travel        287
4  RM829   18    18-25       Yes         Non-Travel        247

               Department  DistanceFromHome  Education EducationField  ...  \
0  RESEARCH & DEVELOPMENT                 3          3  Life Sciences  ...
1                   SALES                10          3        Medical  ...
2                   SALES                 5          3      Marketing  ...
3  RESEARCH & DEVELOPMENT                 5          2  Life Sciences  ...
4  RESEARCH & DEVELOPMENT                 8          1        Medical  ...

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                   0                        0                   0.0
1                   0                        0                   0.0
2                   0                        0                   0.0
3                   0                        0                   0.0
4                   0                        0                   0.0

  Age_Category  Travel_Status  Attrition_Status  DailyRate_Bonus  \
0        Young        Regular      Left Company            253.0
1        Young        Regular           Working            893.2
2        Young       Frequent      Left Company           1436.6
3        Young      No Travel           Working            315.7
4        Young      No Travel      Left Company            271.7

  Distance_Category  Experience_Status MonthlyBonus
0              Near            Fresher         5000
1            Medium            Fresher         7000
2              Near            Fresher         4000
3              Near            Fresher         8000
4            Medium            Fresher         6000

[5 rows x 45 columns]

In [27]:
print(result[["EmpID","Department","MonthlyBonus"]])

   EmpID              Department  MonthlyBonus
0  RM297  RESEARCH & DEVELOPMENT          5000
1  RM302                   SALES          7000
2  RM458                   SALES          4000
3  RM728  RESEARCH & DEVELOPMENT          8000
4  RM829  RESEARCH & DEVELOPMENT          6000

In [28]:
print(result.shape[0])

5