In [140]:
import pandas as pd

In [141]:
df=pd.read_excel(r"C:\Users\USER\Downloads\datacleaning.xlsx")
df

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [142]:
df.head(10)

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
5,1006,Deepa,27,F,HR,"48,000",NaN,15/02/2022,NaN,NaN
6,1007,Priya,Thirty,NaN,NaN,NaN,Bangalore,2024/03/01,NaN,invalidemail
7,1008,Aisha,27,NaN,Marketing,"48,000",NaN,2023-01-15,Excellent,invalidemail
8,1009,Mohammed,NaN,M,NaN,55000,NaN,2023-01-15,NaN,user@example.com
9,1010,Mohammed,25,F,HR,"48,000",Bangalore,NaN,NaN,invalidemail

In [143]:
df.tail(10)

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
90,1091,Aisha,22,M,Sales,35000,Calicut,15/02/2022,good,invalidemail
91,1092,Kiran,NaN,F,Finance,55000,NaN,NaN,Poor,user@example.com
92,1093,Mohammed,Thirty,Male,NaN,55000,Kochi,NaN,Good,NaN
93,1094,Arun,22,F,Sales,35000,Calicut,2024/03/01,Excellent,test@mail.com
94,1095,Deepa,25,Male,Marketing,"48,000",NaN,2024/03/01,good,NaN
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [144]:
df.shape

(100, 10)

In [145]:
df.columns

Index(['EmployeeID', 'Name', 'Age', 'Gender', 'Department', 'Salary', 'City',
       'JoinDate', 'Performance', 'Email'],
      dtype='str')

In [146]:
df.dtypes

EmployeeID      int64
Name              str
Age            object
Gender            str
Department        str
Salary         object
City              str
JoinDate          str
Performance       str
Email             str
dtype: object

In [147]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   100 non-null    int64
 1   Name         100 non-null    str
 2   Age          82 non-null     object
 3   Gender       75 non-null     str
 4   Department   85 non-null     str
 5   Salary       77 non-null     object
 6   City         70 non-null     str
 7   JoinDate     83 non-null     str
 8   Performance  81 non-null     str
 9   Email        75 non-null     str
dtypes: int64(1), object(2), str(7)
memory usage: 7.9+ KB

In [148]:
df.describe()

        EmployeeID
count   100.000000
mean   1050.400000
std      29.151988
min    1001.000000
25%    1025.750000
50%    1050.500000
75%    1075.250000
max    1100.000000

In [149]:
print(df.nunique())

EmployeeID     99
Name           18
Age             6
Gender          4
Department      6
Salary          4
City            5
JoinDate        3
Performance     4
Email           3
dtype: int64

In [150]:
df.isnull().sum()

EmployeeID      0
Name            0
Age            18
Gender         25
Department     15
Salary         23
City           30
JoinDate       17
Performance    19
Email          25
dtype: int64

In [151]:
df.duplicated().sum()

np.int64(0)

In [152]:
df["EmployeeID"].duplicated().sum()

np.int64(1)

In [153]:
df.columns=df.columns.str.lower()
print(df.columns)

Index(['employeeid', 'name', 'age', 'gender', 'department', 'salary', 'city',
       'joindate', 'performance', 'email'],
      dtype='str')

In [154]:
df.columns.str.replace(" ", "_",regex=False)
print(df.columns)

Index(['employeeid', 'name', 'age', 'gender', 'department', 'salary', 'city',
       'joindate', 'performance', 'email'],
      dtype='str')

In [155]:
df["name"] = df["name"].str.title()
df["department"] = df["department"].str.title()
df["city"] = df["city"].str.title()
df["gender"] = df["gender"].str.title()
df["performance"] = df["performance"].str.title()
df["email"] = df["email"].str.title()

print(df)

    employeeid      name     age  gender department  salary       city  \
0         1001     Rahul      22  Female        NaN   55000  Bangalore
1         1002     Kiran      31       M  Marketing     NaN    Calicut
2         1003       Anu  Thirty       F      Sales  48,000        NaN
3         1004      John      27       F  Marketing   35000    Calicut
4         1005     Aisha      25     NaN         It  48,000        NaN
..         ...       ...     ...     ...        ...     ...        ...
95        1096       Anu      27    Male      Sales   42000      Kochi
96        1097  Mohammed      29    Male         Hr   35000        NaN
97        1098       Anu      22    Male         Hr     NaN        NaN
98        1099     Arun       22  Female         It   42000      Kochi
99        1100      Sara      31  Female        It    55000        NaN

      joindate performance             email
0          NaN       Good     Test@Mail.Com
1   2023-01-15         NaN      Invalidemail
2          NaN        Good    Test@Mail.Com
3   15/02/2022       Good   User@Example.Com
4   15/02/2022        Good               NaN
..         ...         ...               ...
95  2024/03/01       Good                NaN
96  15/02/2022   Excellent      Invalidemail
97         NaN       Good     Test@Mail.Com
98  15/02/2022         NaN      Invalidemail
99  2023-01-15        Poor      Invalidemail

[100 rows x 10 columns]

In [156]:
df["age"] = df["age"].replace({
    "Thirty": 30,
    "27": 27
})
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,"48,000",NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,NaN,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000,NaN,2023-01-15,Poor,Invalidemail

In [157]:
df["age"] = df["age"].fillna(df["age"].mean())
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,"48,000",NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,NaN,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000,NaN,2023-01-15,Poor,Invalidemail

In [158]:
df["age"] = df["age"].astype(int)
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,"48,000",NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,NaN,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000,NaN,2023-01-15,Poor,Invalidemail

In [162]:
df["salary"] = df["salary"].replace(",", "",regex = True)
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,48000,NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,48000,NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,NaN,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000,NaN,2023-01-15,Poor,Invalidemail

In [164]:
df["salary"] = df["salary"].astype(float)

In [165]:
df["salary"] = df["salary"].fillna(df["salary"].median())
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,48000.0,NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000.0,NaN,2023-01-15,Poor,Invalidemail

In [166]:
df["department"] = df["department"].fillna(df["department"].mode()[0])
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,NaN,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,48000.0,NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,NaN,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,NaN,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000.0,NaN,2023-01-15,Poor,Invalidemail

In [167]:
df["city"]=df["city"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,NaN,It,48000.0,Unknown,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [169]:
df["gender"] = df["gender"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,NaN,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,NaN,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [170]:
df["performance"] = df["performance"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,NaN
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [171]:
df["email"] = df["email"].fillna("Unknown")
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024/03/01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15/02/2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15/02/2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [173]:
df["joindate"] = df["joindate"].str.replace("/", "-", regex=False)
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,NaN,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,Unknown,NaN,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15-02-2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15-02-2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024-03-01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15-02-2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,NaN,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15-02-2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [174]:
df["joindate"] = df["joindate"].fillna(df["joindate"].mode()[0])
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,2023-01-15,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,Unknown,2023-01-15,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15-02-2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15-02-2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024-03-01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15-02-2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,2023-01-15,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15-02-2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [175]:
df.drop_duplicates()

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,Marketing,55000.0,Bangalore,2023-01-15,Good,Test@Mail.Com
1,1002,Kiran,31,M,Marketing,48000.0,Calicut,2023-01-15,Unknown,Invalidemail
2,1003,Anu,30,F,Sales,48000.0,Unknown,2023-01-15,Good,Test@Mail.Com
3,1004,John,27,F,Marketing,35000.0,Calicut,15-02-2022,Good,User@Example.Com
4,1005,Aisha,25,Unknown,It,48000.0,Unknown,15-02-2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,Kochi,2024-03-01,Good,Unknown
96,1097,Mohammed,29,Male,Hr,35000.0,Unknown,15-02-2022,Excellent,Invalidemail
97,1098,Anu,22,Male,Hr,48000.0,Unknown,2023-01-15,Good,Test@Mail.Com
98,1099,Arun,22,Female,It,42000.0,Kochi,15-02-2022,Unknown,Invalidemail
99,1100,Sara,31,Female,It,55000.0,Unknown,2023-01-15,Poor,Invalidemail

In [176]:
def salary_category(salary):
    if salary < 40000:
        return "Low"
    elif salary <= 60000:
        return "Medium"
    else:
        return "High"

df["salary_category"] = df["salary"].apply(salary_category)

print(df)

    employeeid      name  age   gender department   salary       city  \
0         1001     Rahul   22   Female  Marketing  55000.0  Bangalore
1         1002     Kiran   31        M  Marketing  48000.0    Calicut
2         1003       Anu   30        F      Sales  48000.0    Unknown
3         1004      John   27        F  Marketing  35000.0    Calicut
4         1005     Aisha   25  Unknown         It  48000.0    Unknown
..         ...       ...  ...      ...        ...      ...        ...
95        1096       Anu   27     Male      Sales  42000.0      Kochi
96        1097  Mohammed   29     Male         Hr  35000.0    Unknown
97        1098       Anu   22     Male         Hr  48000.0    Unknown
98        1099     Arun    22   Female         It  42000.0      Kochi
99        1100      Sara   31   Female        It   55000.0    Unknown

      joindate performance             email salary_category
0   2023-01-15       Good     Test@Mail.Com           Medium
1   2023-01-15     Unknown      Invalidemail          Medium
2   2023-01-15        Good    Test@Mail.Com           Medium
3   15-02-2022       Good   User@Example.Com             Low
4   15-02-2022        Good           Unknown          Medium
..         ...         ...               ...             ...
95  2024-03-01       Good            Unknown          Medium
96  15-02-2022   Excellent      Invalidemail             Low
97  2023-01-15       Good     Test@Mail.Com           Medium
98  15-02-2022     Unknown      Invalidemail          Medium
99  2023-01-15        Poor      Invalidemail          Medium

[100 rows x 11 columns]