joins

In [2]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    "Name":["Anu","Arun","Meera"]},index=[1,2,3])
df1

    Name
1    Anu
2   Arun
3  Meera

In [3]:
df2 = pd.DataFrame({
    "Marks":[85,90,95]}, index=[1,2,3])
df2

   Marks
1     85
2     90
3     95

In [4]:
#joins dataframe using the index
df1 = pd.DataFrame({
     "Name":["Anu","Arun","Meera"]},index=[1,2,3])
df2 = pd.DataFrame({
    "Marks":[85,90,95]}, index=[1,2,3])

print(df1.join(df2))

    Name  Marks
1    Anu     85
2   Arun     90
3  Meera     95

concat

In [7]:
df3 =pd.concat([df1,df2]) #default axis =0
df3

    Name  Marks
1    Anu    NaN
2   Arun    NaN
3  Meera    NaN
1    NaN   85.0
2    NaN   90.0
3    NaN   95.0

In [6]:
df3 =pd.concat([df1,df2],axis =1)
df3

    Name  Marks
1    Anu     85
2   Arun     90
3  Meera     95

GroupBy

groups data based on one or more columns and perform aggregate functions

In [8]:
data  = {
    "Department":["HR","IT","HR","IT","Sales"],
    "Salary":[30000,50000,350000,55000,40000]}
df = pd.DataFrame(data)
df

  Department  Salary
0         HR   30000
1         IT   50000
2         HR  350000
3         IT   55000
4      Sales   40000

In [9]:
df.groupby("Department")["Salary"].sum()

Department
HR       380000
IT       105000
Sales     40000
Name: Salary, dtype: int64

In [12]:
print(df.groupby("Department")["Salary"].agg(["sum","mean","max","min","count"]))

               sum      mean     max    min  count
Department
HR          380000  190000.0  350000  30000      2
IT          105000   52500.0   55000  50000      2
Sales        40000   40000.0   40000  40000      1

Apply  function

applies a fucntion to each row or column

In [13]:
df = pd.DataFrame({
    "Marks":[80,90,95,40,39,4]})
df["Bonus"] = df["Marks"].apply(lambda x: x+5)
print(df)

   Marks  Bonus
0     80     85
1     90     95
2     95    100
3     40     45
4     39     44
5      4      9

In [14]:
def passm(x):
    if x>=40:
        return 'pass'
    else:
        return 'fail'

In [15]:
df["Result"] = df["Marks"].apply(passm)
print(df)

   Marks  Bonus Result
0     80     85   pass
1     90     95   pass
2     95    100   pass
3     40     45   pass
4     39     44   fail
5      4      9   fail

In [17]:
df["Result"] = df["Marks"].apply(
    lambda x: "Pass" if x>=40 else "Fail"
)
print(df)

   Marks  Bonus Result
0     80     85   Pass
1     90     95   Pass
2     95    100   Pass
3     40     45   Pass
4     39     44   Fail
5      4      9   Fail

Date and Time

In [22]:
data = {'time': ['2025-01-27 14:45:30', '2025-02-05 0:15:00' , '2025-03-10 20:30:43']}
df =pd.DataFrame(data)
df

                  time
0  2025-01-27 14:45:30
1   2025-02-05 0:15:00
2  2025-03-10 20:30:43

In [20]:
df.dtypes

time    str
dtype: object

In [23]:
#convert to datetime
df['time'] = pd.to_datetime(df['time'])

In [24]:
df.dtypes

time    datetime64[us]
dtype: object

In [26]:
#extract year
df['year'] = df['time'].dt.year

#extract month
df['month'] = df['time'].dt.month

#extract day
df['day'] = df['time'].dt.day

#extract hour
df['hour'] = df['time'].dt.hour

#extract minute
df['minute'] = df['time'].dt.minute

#extract second
df['second'] = df['time'].dt.second

#extract day of the week(mndy = 0,sundy =6)
df['Dayofweek'] =df['time'].dt.dayofweek

#extract day of year
df['Dayofyear'] =df['time'].dt.dayofyear

#extract week number of the year:
df['week'] =df['time'].dt.isocalendar().week

#extract quarter 
df['quarter'] = df['time'].dt.quarter

#get the name of the day(eg : monday)
df['weekday'] = df['time'].dt.day_name()

In [27]:
df

,time,year,month,day,hour,minute,second,Dayofweek,Dayofyear,week,quarter,weekday
0,2025-01-27 14:45:30,2025,1,27,14,45,30,0,27,5,1,Monday
1,2025-02-05 00:15:00,2025,2,5,0,15,0,2,36,6,1,Wednesday
2,2025-03-10 20:30:43,2025,3,10,20,30,43,0,69,11,1,Monday

Data validation

In [13]:
#check missing values
df =pd.DataFrame({
    "Name":["Anu","Arun",None,"Anu"],
    "Marks":[65,None,90,65]
})
df

   Name  Marks
0   Anu   65.0
1  Arun    NaN
2   NaN   90.0
3   Anu   65.0

In [14]:
#df.isna().sum()
df.isnull()

    Name  Marks
0  False  False
1  False   True
2   True  False
3  False  False

In [15]:
print(df.isnull().sum())

Name     1
Marks    1
dtype: int64

In [16]:
#duplicate rows
print(df.duplicated())

0    False
1    False
2    False
3     True
dtype: bool

In [17]:
print(df.duplicated().sum())

1

In [18]:
#remove duplicates
df.drop_duplicates(inplace=True)

In [19]:
df

   Name  Marks
0   Anu   65.0
1  Arun    NaN
2   NaN   90.0

In [20]:
print(df.dtypes)

Name         str
Marks    float64
dtype: object

In [21]:
#validate numeric range
df =pd.DataFrame({
    "Age":[20,25,17,45]
})
print(df[df["Age"] >= 18])

   Age
0   20
1   25
3   45

Data Transformation

converts data into a suitable format for analysis

In [22]:
#reanme column
df.rename(columns ={"Age":"Students_age"},inplace= True)
print(df)

   Students_age
0            20
1            25
2            17
3            45

In [23]:
df.Students_age.dtypes

dtype('int64')

In [24]:
#change datatype
df["Students_age"]=df["Students_age"].astype("int32")
print(df.dtypes)

Students_age    int32
dtype: object

In [25]:
#create new column
df["age_after_5_years"]=df["Students_age"] + 5
print(df)

   Students_age  age_after_5_years
0            20                 25
1            25                 30
2            17                 22
3            45                 50

In [26]:
#replace values
df = pd.DataFrame({
    "Gender":["M","F","M"]
})
df["Gender"] = df["Gender"].replace({
    "M" :"Male",
    "F":"Female"
})
print(df)

   Gender
0    Male
1  Female
2    Male

In [29]:
#convert text to uppercase
df = pd.DataFrame({
    "Name":["Anu","arun","meera"]
})
df["Name1"] = df["Name"].str.upper()
print(df)

    Name  Name1
0    Anu    ANU
1   arun   ARUN
2  meera  MEERA

In [30]:
#convert to lower case
df["Name2"] = df["Name"].str.lower()
print(df)

    Name  Name1  Name2
0    Anu    ANU    anu
1   arun   ARUN   arun
2  meera  MEERA  meera

In [32]:
#remove spaces
df = pd.DataFrame({
    "Name":["  Anu","  Arun","  Meera"]
})
df["Name"] =df["Name"].str.strip()
print(df)

    Name
0    Anu
1   Arun
2  Meera