In [2]:
import pandas as pd

#methods to create dataframe 
1 nested list
2 list of dict
3 dict of list

In [3]:
li =[ ["swetha",21,"btech" ],
      ["nandana",20,"bca"],
      ["manu",19,"bba"],
      ["vinod",11,"bcom"]
    ]
df = pd.DataFrame(li,columns =['name','age','dept'])
(df)

      name  age   dept
0   swetha   21  btech
1  nandana   20    bca
2     manu   19    bba
3    vinod   11   bcom

In [4]:
print(df.shape)
print(df.size)
print(df.ndim)

(4, 3)
12
2

In [5]:
#column name
df = pd.DataFrame(li, columns = ['name','age','dpt'])
df

      name  age    dpt
0   swetha   21  btech
1  nandana   20    bca
2     manu   19    bba
3    vinod   11   bcom

In [6]:
#dict of list
dic = {"Name":["Anu","Adhil","kavya","vinod"],
        "roll no" :[10,12,23,45],
        "Batch":["Bca","bcom","bba","ba"]}
df=pd.DataFrame(dic)
df

    Name  roll no Batch
0    Anu       10   Bca
1  Adhil       12  bcom
2  kavya       23   bba
3  vinod       45    ba

In [7]:
#list of dict
lis =[
    {'name':'Anu','roll no':10,'batch':'bca'},
     {'name': 'Manu','roll no':11,'batch':'bba'},
    {'name':'Vinod','roll no': 12,'batch':'BA'}
]
df= pd.DataFrame(lis)
df

    name  roll no batch
0    Anu       10   bca
1   Manu       11   bba
2  Vinod       12    BA

In [8]:
#nested list
li =[ [1,"Swetha","developer",50000],
      [2,"nandana","data analyst",650000],
      [3,"manu","Hr",250000],
      [4,"vinod","designer",450000]
    ]
df = pd.DataFrame(li,columns =["empid","empname","designation","salary"])
(df)

   empid  empname   designation  salary
0      1   Swetha     developer   50000
1      2  nandana  data analyst  650000
2      3     manu            Hr  250000
3      4    vinod      designer  450000

In [9]:
#dict of list
dic = {"empid" :[1,2,3,4],
        "empname":["swetha","nandana","manu","anu"],
        "designation":["data analyst","developer","Hr","designer"],
        "salary" :[50000,450000,60000,34000]}
df =pd.DataFrame(dic)
df

   empid  empname   designation  salary
0      1   swetha  data analyst   50000
1      2  nandana     developer  450000
2      3     manu            Hr   60000
3      4      anu      designer   34000

In [10]:
#list of dict
lis =[
    {'empid':1,'empname':'swetha','designation':'data analyst','salary':50000},
     {'empid':2,'empname':'nandana','designation':'developer','salary':45000},
    {'empid':3,'empname':'manu' ,'designation':'Hr','salary':56000},
    {'empid':4,'empname':'anu','designation':'Designer','salary':34000}
]
df= pd.DataFrame(lis)
df

   empid  empname   designation  salary
0      1   swetha  data analyst   50000
1      2  nandana     developer   45000
2      3     manu            Hr   56000
3      4      anu      Designer   34000

In [11]:
df.head(2)

   empid  empname   designation  salary
0      1   swetha  data analyst   50000
1      2  nandana     developer   45000

In [12]:
df.tail(2)

   empid empname designation  salary
2      3    manu          Hr   56000
3      4     anu    Designer   34000

In [13]:
df.columns

Index(['empid', 'empname', 'designation', 'salary'], dtype='str')

In [14]:
df.dtypes

empid          int64
empname          str
designation      str
salary         int64
dtype: object

In [15]:
df['empname'].dtypes

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   empid        4 non-null      int64
 1   empname      4 non-null      str
 2   designation  4 non-null      str
 3   salary       4 non-null      int64
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

In [17]:
#statistical summary
df.describe()

          empid        salary
count  4.000000      4.000000
mean   2.500000  46250.000000
std    1.290994   9322.910847
min    1.000000  34000.000000
25%    1.750000  42250.000000
50%    2.500000  47500.000000
75%    3.250000  51500.000000
max    4.000000  56000.000000

In [18]:
#including objects
df.describe(include ='object')

C:\Users\USER\AppData\Local\Temp\ipykernel_11988\3256468843.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include ='object')

       empname   designation
count        4             4
unique       4             4
top     swetha  data analyst
freq         1             1

In [19]:
df['empname']

0     swetha
1    nandana
2       manu
3        anu
Name: empname, dtype: str

In [20]:
df[['empname','designation']]

   empname   designation
0   swetha  data analyst
1  nandana     developer
2     manu            Hr
3      anu      Designer

In [21]:
#select row using loc -label based
df.loc[1]

empid                  2
empname          nandana
designation    developer
salary             45000
Name: 1, dtype: object

In [22]:
#use both integer based
df.iloc[0:3][['salary']]

   salary
0   50000
1   45000
2   56000

In [23]:
print(df.iloc[1])

empid                  2
empname          nandana
designation    developer
salary             45000
Name: 1, dtype: object

In [24]:
#to add new column
df["points"]=[122,234,190,111]
print(df)

   empid  empname   designation  salary  points
0      1   swetha  data analyst   50000     122
1      2  nandana     developer   45000     234
2      3     manu            Hr   56000     190
3      4      anu      Designer   34000     111

In [25]:
#update a value using index
df.iloc[3,4] = 55
print(df)

   empid  empname   designation  salary  points
0      1   swetha  data analyst   50000     122
1      2  nandana     developer   45000     234
2      3     manu            Hr   56000     190
3      4      anu      Designer   34000      55

In [26]:
df.loc[1,'points'] = 670
df

   empid  empname   designation  salary  points
0      1   swetha  data analyst   50000     122
1      2  nandana     developer   45000     670
2      3     manu            Hr   56000     190
3      4      anu      Designer   34000      55

In [27]:
#drop is used to delete columns,axis 1 denotes columns,inplace is used to permanantly delete those columns)
df.drop('points',axis=1,inplace = True)
df

   empid  empname   designation  salary
0      1   swetha  data analyst   50000
1      2  nandana     developer   45000
2      3     manu            Hr   56000
3      4      anu      Designer   34000

In [28]:
df.drop(2)

   empid  empname   designation  salary
0      1   swetha  data analyst   50000
1      2  nandana     developer   45000
3      4      anu      Designer   34000

In [29]:
#filtering data
df1 =df[df['empid']<3]
df1

   empid  empname   designation  salary
0      1   swetha  data analyst   50000
1      2  nandana     developer   45000

In [30]:
#sorting data based on empname
df.sort_values(by ='empname')

   empid  empname   designation  salary
3      4      anu      Designer   34000
2      3     manu            Hr   56000
1      2  nandana     developer   45000
0      1   swetha  data analyst   50000

In [31]:
#for descending order sorting
df.sort_values("empname", ascending= False)

   empid  empname   designation  salary
0      1   swetha  data analyst   50000
1      2  nandana     developer   45000
2      3     manu            Hr   56000
3      4      anu      Designer   34000

In [32]:
pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
df=pd.read_excel(r"C:\Users\USER\Downloads\gender.xlsx")
df

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [34]:
df.drop([1,5,8])

     PassengerId  Survived
0            892         0
2            894         0
3            895         0
4            896         1
6            898         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[415 rows x 2 columns]

In [35]:
#sort row
df2 = df[df['Survived']>0]
df2

     PassengerId  Survived
1            893         1
4            896         1
6            898         1
8            900         1
12           904         1
..           ...       ...
409         1301         1
410         1302         1
411         1303         1
412         1304         1
414         1306         1

[152 rows x 2 columns]

In [36]:
df2.reset_index(drop=True)

     PassengerId  Survived
0            893         1
1            896         1
2            898         1
3            900         1
4            904         1
..           ...       ...
147         1301         1
148         1302         1
149         1303         1
150         1304         1
151         1306         1

[152 rows x 2 columns]

In [37]:
df.to_csv("output.csv")

In [38]:
df = pd.read_csv(r"C:\Users\USER\Downloads\fifa_world_cup_2026_player_performance-selected-columns.csv")
df

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left
...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right

In [39]:
df.drop(['player_id','player_name','age'],axis =1,inplace = True)
df

,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
0,Spanish,Spain,3,Goalkeeper,195,75,Left
1,Spanish,Spain,18,Midfielder,178,75,Right
2,Spanish,Spain,14,Midfielder,177,72,Left
3,Spanish,Spain,21,Forward,182,74,Right
4,Spanish,Spain,7,Defender,191,81,Left
...,...,...,...,...,...,...,...
54595,Iraqi,Iraq,8,Defender,177,73,Right
54596,Iraqi,Iraq,18,Midfielder,176,72,Right
54597,Iraqi,Iraq,20,Midfielder,173,77,Left
54598,Iraqi,Iraq,3,Goalkeeper,190,81,Right
54599,Iraqi,Iraq,1,Goalkeeper,187,73,Right

In [40]:
df['team'].dtypes

In [41]:
df.iloc[1:11][['team','position']]

     team    position
1   Spain  Midfielder
2   Spain  Midfielder
3   Spain     Forward
4   Spain    Defender
5   Spain  Midfielder
6   Spain    Defender
7   Spain     Forward
8   Spain    Defender
9   Spain     Forward
10  Spain  Midfielder

In [42]:
df.sort_values(by = 'jersey_number',ascending=False)

,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
54558,Senegalese,Senegal,26,Forward,186,78,Right
7,Spanish,Spain,26,Forward,182,72,Right
21023,Nigerian,Nigeria,26,Forward,185,74,Left
21002,Serbian,Serbia,26,Forward,170,72,Right
47740,Qatari,Qatar,26,Forward,181,77,Left
...,...,...,...,...,...,...,...
40897,Colombian,Colombia,1,Goalkeeper,192,85,Right
40898,Italian,Italy,1,Goalkeeper,187,75,Right
40870,Jamaican,Jamaica,1,Goalkeeper,190,77,Right
48281,Tunisian,Tunisia,1,Goalkeeper,190,81,Left
48282,Ecuadorian,Ecuador,1,Goalkeeper,185,74,Right

In [43]:
df.sort_values(by ='jersey_number').tail(1)

,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
15907,Chilean,Chile,26,Forward,175,76,Right

In [44]:
df.reset_index(drop=True)

,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
0,Spanish,Spain,3,Goalkeeper,195,75,Left
1,Spanish,Spain,18,Midfielder,178,75,Right
2,Spanish,Spain,14,Midfielder,177,72,Left
3,Spanish,Spain,21,Forward,182,74,Right
4,Spanish,Spain,7,Defender,191,81,Left
...,...,...,...,...,...,...,...
54595,Iraqi,Iraq,8,Defender,177,73,Right
54596,Iraqi,Iraq,18,Midfielder,176,72,Right
54597,Iraqi,Iraq,20,Midfielder,173,77,Left
54598,Iraqi,Iraq,3,Goalkeeper,190,81,Right
54599,Iraqi,Iraq,1,Goalkeeper,187,73,Right

In [45]:
df['position'].unique()

<StringArray>
['Goalkeeper', 'Midfielder', 'Forward', 'Defender']
Length: 4, dtype: str

In [46]:
df['position'].nunique()

4

In [47]:
df['position'].value_counts()

position
Defender      18900
Midfielder    16800
Forward       12600
Goalkeeper     6300
Name: count, dtype: int64

In [48]:
df2 = df.loc[df['position']=='Defender']
df2

,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
4,Spanish,Spain,7,Defender,191,81,Left
6,Spanish,Spain,6,Defender,188,80,Right
8,Spanish,Spain,4,Defender,176,78,Left
14,Spanish,Spain,5,Defender,187,76,Right
15,Spanish,Spain,10,Defender,175,73,Right
...,...,...,...,...,...,...,...
54584,Iraqi,Iraq,7,Defender,188,84,Left
54585,Iraqi,Iraq,11,Defender,187,80,Right
54588,Iraqi,Iraq,10,Defender,190,78,Left
54590,Iraqi,Iraq,6,Defender,180,78,Right
54595,Iraqi,Iraq,8,Defender,177,73,Right

In [49]:
df2 =df.loc[(df['position']=='Defender') & (df['jersey_number']>10)]
df2

,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot
17,Spanish,Spain,12,Defender,181,80,Left
22,Spanish,Spain,11,Defender,183,80,Right
35,South African,South Africa,11,Defender,190,81,Right
41,South African,South Africa,12,Defender,184,80,Right
53,Peruvian,Peru,11,Defender,187,79,Right
...,...,...,...,...,...,...,...
54545,Brazilian,Brazil,12,Defender,185,77,Right
54553,Senegalese,Senegal,11,Defender,185,81,Left
54565,Senegalese,Senegal,12,Defender,183,77,Right
54582,Iraqi,Iraq,12,Defender,184,75,Left
54585,Iraqi,Iraq,11,Defender,187,80,Right

In [50]:
df2 =df.loc[(df['position']=='Defender') & (df['jersey_number']>10)].sort_values(by='jersey_number').tail(1)[['team']]
df2

          team
54472  Senegal

merge()

In [112]:
df1 = pd.DataFrame({
    'empid': [101,102,103,104,105],
    'empname' : ['anand','bavish','catherine','davis','ellas'],
    'designation' : ['doctor','engineer','advocate','teacher','developer']})
df1

   empid    empname designation
0    101      anand      doctor
1    102     bavish    engineer
2    103  catherine    advocate
3    104      davis     teacher
4    105      ellas   developer

In [114]:
df2 =pd.DataFrame({
    'empid': [101,102,103,106,107],
    'salaray' :[20000,203000,30000,28000,22000],
    'location':['ekm','kollam','kottayam','aluva','thrissur']})
df2

   empid  salaray  location
0    101    20000       ekm
1    102   203000    kollam
2    103    30000  kottayam
3    106    28000     aluva
4    107    22000  thrissur

In [115]:
df =pd.merge(df1,df2,how='inner',on='empid')
df

   empid    empname designation  salaray  location
0    101      anand      doctor    20000       ekm
1    102     bavish    engineer   203000    kollam
2    103  catherine    advocate    30000  kottayam

In [116]:
df = pd.merge(df1,df2,how='outer',on='empid')
df

   empid    empname designation   salaray  location
0    101      anand      doctor   20000.0       ekm
1    102     bavish    engineer  203000.0    kollam
2    103  catherine    advocate   30000.0  kottayam
3    104      davis     teacher       NaN       NaN
4    105      ellas   developer       NaN       NaN
5    106        NaN         NaN   28000.0     aluva
6    107        NaN         NaN   22000.0  thrissur

In [117]:
df = pd.merge(df1,df2,how='left',on='empid')
df

   empid    empname designation   salaray  location
0    101      anand      doctor   20000.0       ekm
1    102     bavish    engineer  203000.0    kollam
2    103  catherine    advocate   30000.0  kottayam
3    104      davis     teacher       NaN       NaN
4    105      ellas   developer       NaN       NaN

In [118]:
df = pd.merge(df1,df2,how='right',on='empid')
df

   empid    empname designation  salaray  location
0    101      anand      doctor    20000       ekm
1    102     bavish    engineer   203000    kollam
2    103  catherine    advocate    30000  kottayam
3    106        NaN         NaN    28000     aluva
4    107        NaN         NaN    22000  thrissur

In [120]:
df.dtypes

empid          int64
empname          str
designation      str
salaray        int64
location         str
dtype: object

In [124]:
import warnings
warnings.filterwarnings('ignore')

In [123]:
#change datatype of empid (to float)
df['empid']=df['empid'].astype('float')

In [122]:
df.dtypes

empid          float64
empname            str
designation        str
salaray          int64
location           str
dtype: object